### ISSUE TITLE
Add support for search configurations (Embedding + Vector store)

### ISSUE THREAD

**Issue by vhoudebine** [vhoudebine/azure-pf-benchmarking-tool#3]
Need to make it possible to define a search configuration, Embeddings and Vector search are very closely tied so it doesn't make sense to have these defined separately. I'm thinking something like

```
search:
    - config1:
       - embedding:
               -  connection:
               - family: AZUREOPENAI
        - vector_store:
              - connection: aisearch
              - search_index: doc_embeddings
              - vector_field: vector_content
     - config2:
        - embedding:
               -  connection:
               - family: COHERE
        - vector_store:
              - connection: pinecone
              - search_index: doc_embeddings
              - vector_field: vector_content

```
